/**
 * Extra recipe seed data (Session 20) — ~100 healthy, student-friendly meals
 * built around common basic products so the photo / pantry recommendation flow
 * can return dishes the user can actually cook. Imported and concatenated by
 * prisma/seed.ts. Every recipe carries full macros (calories/protein/fat/carbs),
 * a difficulty, an estimated per-serving cost, mood tags and an ingredient list
 * with categories (used for dietary filtering and health scoring).
 *
 * Coverage is deliberately weighted toward staples people keep at home:
 * eggs, chicken, rice, pasta, oats, potato, beans, lentils, chickpeas, tuna,
 * yogurt, cheese, bread, and everyday vegetables & fruit.
 */

export interface SeedRecipe {
  title: string
  cookingTimeMin: number
  difficulty: 'easy' | 'medium' | 'hard'
  estimatedCost: number
  calories: number
  proteinG: number
  fatG: number
  carbsG: number
  steps: string
  moodTags: string[]
  ingredients: Array<{ name: string; category: string; amount: string; unit: string }>
}

export const extraRecipes: SeedRecipe[] = [
  // ─── Eggs (very common fridge staple) ───────────────────────────────────────
  {
    title: 'Classic Boiled Eggs on Toast',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 2.0,
    calories: 290, proteinG: 18, fatG: 14, carbsG: 24,
    steps: 'Boil eggs 7 minutes, peel and slice over buttered wholegrain toast, season with salt and pepper.',
    moodTags: ['energetic', 'focused', 'cozy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'whole wheat bread', category: 'grain', amount: '2', unit: 'slices' },
    ],
  },
  {
    title: 'Tomato Scrambled Eggs',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 2.5,
    calories: 310, proteinG: 20, fatG: 20, carbsG: 8,
    steps: 'Sauté chopped tomato briefly, pour in beaten eggs and scramble softly until just set.',
    moodTags: ['happy', 'energetic', 'calm'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '3', unit: 'pcs' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tsp' },
    ],
  },
  {
    title: 'Spinach Feta Egg Muffins',
    cookingTimeMin: 22, difficulty: 'easy', estimatedCost: 3.5,
    calories: 230, proteinG: 20, fatG: 15, carbsG: 5,
    steps: 'Whisk eggs with chopped spinach and crumbled feta, pour into a muffin tin and bake at 180°C for 18 minutes.',
    moodTags: ['focused', 'energetic'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '4', unit: 'pcs' },
      { name: 'spinach', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'feta', category: 'dairy', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Shakshuka',
    cookingTimeMin: 25, difficulty: 'medium', estimatedCost: 3.5,
    calories: 320, proteinG: 18, fatG: 18, carbsG: 22,
    steps: 'Simmer onion, bell pepper and canned tomatoes with paprika, crack eggs into the sauce and cook until set.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '3', unit: 'pcs' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Egg & Cheese Breakfast Wrap',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 3.0,
    calories: 380, proteinG: 22, fatG: 18, carbsG: 34,
    steps: 'Scramble eggs, fold into a tortilla with grated cheese and a handful of spinach.',
    moodTags: ['energetic', 'happy', 'cozy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'flour tortilla', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '30', unit: 'g' },
    ],
  },
  {
    title: 'Potato & Egg Hash',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 3.0,
    calories: 420, proteinG: 18, fatG: 18, carbsG: 48,
    steps: 'Pan-fry diced potato until golden, add bell pepper and onion, then make wells and crack in the eggs to finish.',
    moodTags: ['cozy', 'happy'],
    ingredients: [
      { name: 'potato', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Mushroom Cheese Omelette',
    cookingTimeMin: 12, difficulty: 'easy', estimatedCost: 3.0,
    calories: 340, proteinG: 22, fatG: 24, carbsG: 6,
    steps: 'Sauté sliced mushrooms, pour over beaten eggs, scatter cheese and fold once set.',
    moodTags: ['focused', 'calm', 'cozy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '3', unit: 'pcs' },
      { name: 'mushrooms', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Egg Salad Sandwich',
    cookingTimeMin: 12, difficulty: 'easy', estimatedCost: 2.5,
    calories: 360, proteinG: 20, fatG: 18, carbsG: 30,
    steps: 'Mash boiled eggs with yogurt and mustard, spread between wholegrain bread with lettuce.',
    moodTags: ['calm', 'happy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '3', unit: 'pcs' },
      { name: 'whole wheat bread', category: 'grain', amount: '2', unit: 'slices' },
      { name: 'greek yogurt', category: 'dairy', amount: '30', unit: 'g' },
      { name: 'lettuce', category: 'vegetable', amount: '20', unit: 'g' },
    ],
  },
  {
    title: 'Zucchini Egg Fritters',
    cookingTimeMin: 20, difficulty: 'easy', estimatedCost: 3.0,
    calories: 280, proteinG: 16, fatG: 16, carbsG: 18,
    steps: 'Grate and squeeze zucchini, mix with eggs and flour, pan-fry spoonfuls until golden on both sides.',
    moodTags: ['happy', 'energetic', 'calm'],
    ingredients: [
      { name: 'zucchini', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'flour', category: 'grain', amount: '40', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Egg Drop Soup',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 2.5,
    calories: 180, proteinG: 14, fatG: 9, carbsG: 10,
    steps: 'Bring broth to a simmer, stir in a slurry, then drizzle beaten egg in slow ribbons and add green onion.',
    moodTags: ['cozy', 'calm'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'vegetable broth', category: 'liquid', amount: '500', unit: 'ml' },
      { name: 'green onion', category: 'vegetable', amount: '2', unit: 'pcs' },
    ],
  },

  // ─── Chicken (the most-requested protein) ───────────────────────────────────
  {
    title: 'Garlic Butter Chicken & Rice',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 5.0,
    calories: 520, proteinG: 42, fatG: 16, carbsG: 50,
    steps: 'Sear diced chicken in garlic, serve over white rice with steamed green peas.',
    moodTags: ['energetic', 'focused', 'cozy'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '200', unit: 'g' },
      { name: 'white rice', category: 'grain', amount: '120', unit: 'g' },
      { name: 'green peas', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Honey Mustard Baked Chicken',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 5.5,
    calories: 410, proteinG: 44, fatG: 14, carbsG: 18,
    steps: 'Coat chicken in honey, mustard and garlic, bake at 200°C for 25 minutes, rest before slicing.',
    moodTags: ['focused', 'energetic'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '220', unit: 'g' },
      { name: 'honey', category: 'sweetener', amount: '1', unit: 'tbsp' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Chicken Caesar-Style Salad',
    cookingTimeMin: 20, difficulty: 'easy', estimatedCost: 5.5,
    calories: 380, proteinG: 40, fatG: 18, carbsG: 14,
    steps: 'Grill chicken, slice over romaine with a yogurt-lemon dressing and a little grated parmesan.',
    moodTags: ['energetic', 'focused', 'calm'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '180', unit: 'g' },
      { name: 'lettuce', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'greek yogurt', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'parmesan', category: 'dairy', amount: '20', unit: 'g' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Chicken Fajita Bowl',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 5.5,
    calories: 490, proteinG: 40, fatG: 15, carbsG: 48,
    steps: 'Stir-fry chicken strips with bell pepper and onion, serve over rice with black beans and salsa.',
    moodTags: ['happy', 'energetic'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '180', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'brown rice', category: 'grain', amount: '80', unit: 'g' },
      { name: 'black beans', category: 'legume', amount: '80', unit: 'g' },
      { name: 'salsa', category: 'condiment', amount: '50', unit: 'g' },
    ],
  },
  {
    title: 'Chicken Noodle Soup',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 4.0,
    calories: 340, proteinG: 30, fatG: 9, carbsG: 38,
    steps: 'Simmer chicken with carrot, onion and celery, add noodles and cook until tender.',
    moodTags: ['cozy', 'calm', 'focused'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '150', unit: 'g' },
      { name: 'noodles', category: 'grain', amount: '80', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Teriyaki Chicken Stir-Fry',
    cookingTimeMin: 22, difficulty: 'easy', estimatedCost: 5.5,
    calories: 470, proteinG: 38, fatG: 14, carbsG: 46,
    steps: 'Stir-fry chicken and mixed vegetables, toss in soy sauce and honey, serve over rice.',
    moodTags: ['energetic', 'happy'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '180', unit: 'g' },
      { name: 'broccoli', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'white rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'soy sauce', category: 'condiment', amount: '2', unit: 'tbsp' },
      { name: 'honey', category: 'sweetener', amount: '1', unit: 'tsp' },
    ],
  },
  {
    title: 'Chicken & Vegetable Pasta',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 5.0,
    calories: 540, proteinG: 38, fatG: 14, carbsG: 62,
    steps: 'Cook pasta, toss with pan-seared chicken, cherry tomatoes, spinach and olive oil.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '180', unit: 'g' },
      { name: 'pasta', category: 'grain', amount: '100', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '40', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Baked Chicken Thighs with Potato',
    cookingTimeMin: 40, difficulty: 'easy', estimatedCost: 5.0,
    calories: 560, proteinG: 40, fatG: 26, carbsG: 38,
    steps: 'Roast chicken thighs with potato wedges, garlic and herbs at 200°C until crisp.',
    moodTags: ['cozy', 'happy'],
    ingredients: [
      { name: 'chicken thigh', category: 'meat', amount: '2', unit: 'pcs' },
      { name: 'potato', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'garlic', category: 'vegetable', amount: '3', unit: 'cloves' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Chicken Quesadilla',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 4.5,
    calories: 520, proteinG: 36, fatG: 22, carbsG: 44,
    steps: 'Fill a tortilla with shredded chicken, cheese and bell pepper, toast in a dry pan until golden.',
    moodTags: ['happy', 'cozy', 'energetic'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '150', unit: 'g' },
      { name: 'flour tortilla', category: 'grain', amount: '2', unit: 'pcs' },
      { name: 'cheese', category: 'dairy', amount: '50', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Lemon Herb Chicken & Quinoa',
    cookingTimeMin: 28, difficulty: 'medium', estimatedCost: 6.0,
    calories: 480, proteinG: 42, fatG: 16, carbsG: 40,
    steps: 'Marinate chicken in lemon and herbs, pan-cook, serve over quinoa with cucumber salad.',
    moodTags: ['focused', 'energetic', 'calm'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '180', unit: 'g' },
      { name: 'quinoa', category: 'grain', amount: '80', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
    ],
  },

  // ─── Rice & grain bowls ─────────────────────────────────────────────────────
  {
    title: 'Vegetable Khichdi',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 3.0,
    calories: 400, proteinG: 16, fatG: 8, carbsG: 70,
    steps: 'Simmer rice and red lentils with carrot, peas and turmeric until soft and porridge-like.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'white rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'red lentils', category: 'legume', amount: '80', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'green peas', category: 'vegetable', amount: '50', unit: 'g' },
      { name: 'turmeric', category: 'spice', amount: '0.5', unit: 'tsp' },
    ],
  },
  {
    title: 'Kimchi-Style Fried Rice',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 3.5,
    calories: 430, proteinG: 14, fatG: 12, carbsG: 66,
    steps: 'Stir-fry cooked rice with chopped cabbage, green onion and soy sauce, top with a fried egg.',
    moodTags: ['energetic', 'happy'],
    ingredients: [
      { name: 'white rice', category: 'grain', amount: '150', unit: 'g' },
      { name: 'cabbage', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'green onion', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'eggs', category: 'dairy', amount: '1', unit: 'pc' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Brown Rice Burrito Bowl',
    cookingTimeMin: 20, difficulty: 'easy', estimatedCost: 4.0,
    calories: 470, proteinG: 18, fatG: 12, carbsG: 72,
    steps: 'Layer brown rice with black beans, corn, tomato and avocado, finish with lime.',
    moodTags: ['happy', 'energetic', 'calm'],
    ingredients: [
      { name: 'brown rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'black beans', category: 'legume', amount: '150', unit: 'g' },
      { name: 'sweet corn', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'avocado', category: 'fruit', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Buckwheat with Mushrooms',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 3.0,
    calories: 380, proteinG: 14, fatG: 12, carbsG: 58,
    steps: 'Cook buckwheat, sauté mushrooms and onion, fold together and season.',
    moodTags: ['cozy', 'calm', 'focused'],
    ingredients: [
      { name: 'buckwheat', category: 'grain', amount: '100', unit: 'g' },
      { name: 'mushrooms', category: 'vegetable', amount: '120', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Coconut Chickpea Rice',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 3.5,
    calories: 450, proteinG: 16, fatG: 16, carbsG: 62,
    steps: 'Simmer rice with chickpeas, coconut milk and spinach until creamy.',
    moodTags: ['cozy', 'happy', 'calm'],
    ingredients: [
      { name: 'white rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'chickpeas', category: 'legume', amount: '150', unit: 'g' },
      { name: 'coconut milk', category: 'dairy-free', amount: '100', unit: 'ml' },
      { name: 'spinach', category: 'vegetable', amount: '50', unit: 'g' },
    ],
  },
  {
    title: 'Bulgur Tabbouleh',
    cookingTimeMin: 20, difficulty: 'easy', estimatedCost: 3.0,
    calories: 320, proteinG: 10, fatG: 12, carbsG: 46,
    steps: 'Soak bulgur, toss with parsley, tomato, cucumber, lemon and olive oil.',
    moodTags: ['calm', 'happy', 'focused'],
    ingredients: [
      { name: 'bulgur', category: 'grain', amount: '80', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Quinoa Black Bean Power Bowl',
    cookingTimeMin: 22, difficulty: 'easy', estimatedCost: 4.0,
    calories: 440, proteinG: 20, fatG: 14, carbsG: 60,
    steps: 'Combine cooked quinoa with black beans, corn, bell pepper and a lime-olive oil dressing.',
    moodTags: ['energetic', 'focused', 'happy'],
    ingredients: [
      { name: 'quinoa', category: 'grain', amount: '80', unit: 'g' },
      { name: 'black beans', category: 'legume', amount: '150', unit: 'g' },
      { name: 'sweet corn', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Pea & Mint Risotto',
    cookingTimeMin: 35, difficulty: 'medium', estimatedCost: 4.5,
    calories: 460, proteinG: 16, fatG: 14, carbsG: 66,
    steps: 'Cook arborio rice with broth gradually, stir in green peas and parmesan at the end.',
    moodTags: ['cozy', 'calm'],
    ingredients: [
      { name: 'arborio rice', category: 'grain', amount: '150', unit: 'g' },
      { name: 'green peas', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'parmesan', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'vegetable broth', category: 'liquid', amount: '500', unit: 'ml' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Sweet Potato Rice Bowl',
    cookingTimeMin: 28, difficulty: 'easy', estimatedCost: 3.5,
    calories: 420, proteinG: 12, fatG: 12, carbsG: 70,
    steps: 'Roast sweet potato cubes, serve over brown rice with chickpeas and a tahini drizzle.',
    moodTags: ['calm', 'happy', 'cozy'],
    ingredients: [
      { name: 'sweet potato', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'brown rice', category: 'grain', amount: '80', unit: 'g' },
      { name: 'chickpeas', category: 'legume', amount: '120', unit: 'g' },
      { name: 'tahini', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Couscous with Roasted Vegetables',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 3.5,
    calories: 400, proteinG: 12, fatG: 12, carbsG: 62,
    steps: 'Roast zucchini, bell pepper and onion, fluff couscous and combine with lemon.',
    moodTags: ['happy', 'calm', 'energetic'],
    ingredients: [
      { name: 'couscous', category: 'grain', amount: '80', unit: 'g' },
      { name: 'zucchini', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },

  // ─── Pasta ──────────────────────────────────────────────────────────────────
  {
    title: 'Tomato Basil Pasta',
    cookingTimeMin: 20, difficulty: 'easy', estimatedCost: 2.5,
    calories: 480, proteinG: 14, fatG: 12, carbsG: 78,
    steps: 'Simmer canned tomatoes with garlic and basil, toss with cooked pasta.',
    moodTags: ['happy', 'cozy', 'calm'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '120', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Tuna Pasta Salad',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 3.5,
    calories: 460, proteinG: 30, fatG: 12, carbsG: 60,
    steps: 'Toss cooled pasta with canned tuna, sweet corn, cherry tomato and a light yogurt dressing.',
    moodTags: ['energetic', 'happy', 'focused'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '100', unit: 'g' },
      { name: 'canned tuna', category: 'fish', amount: '1', unit: 'can' },
      { name: 'sweet corn', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'greek yogurt', category: 'dairy', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Creamy Spinach Pasta',
    cookingTimeMin: 22, difficulty: 'easy', estimatedCost: 3.5,
    calories: 520, proteinG: 18, fatG: 18, carbsG: 70,
    steps: 'Wilt spinach with garlic, stir through cream cheese and pasta water, toss with pasta.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '120', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'cream cheese', category: 'dairy', amount: '50', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Pasta Primavera',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 4.0,
    calories: 470, proteinG: 16, fatG: 14, carbsG: 70,
    steps: 'Sauté broccoli, bell pepper, carrot and peas, toss with pasta, olive oil and parmesan.',
    moodTags: ['happy', 'energetic', 'calm'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '110', unit: 'g' },
      { name: 'broccoli', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'parmesan', category: 'dairy', amount: '30', unit: 'g' },
    ],
  },
  {
    title: 'Lentil Bolognese',
    cookingTimeMin: 35, difficulty: 'medium', estimatedCost: 3.5,
    calories: 500, proteinG: 24, fatG: 12, carbsG: 78,
    steps: 'Simmer red lentils with canned tomatoes, onion, carrot and herbs, serve over pasta.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '110', unit: 'g' },
      { name: 'red lentils', category: 'legume', amount: '100', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Garlic Mushroom Pasta',
    cookingTimeMin: 22, difficulty: 'easy', estimatedCost: 3.5,
    calories: 490, proteinG: 16, fatG: 16, carbsG: 72,
    steps: 'Sauté mushrooms and garlic in olive oil, toss with pasta and a handful of parsley.',
    moodTags: ['cozy', 'focused', 'calm'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '120', unit: 'g' },
      { name: 'mushrooms', category: 'vegetable', amount: '150', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '3', unit: 'cloves' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Chicken Pesto Pasta',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 5.5,
    calories: 580, proteinG: 38, fatG: 22, carbsG: 58,
    steps: 'Toss cooked pasta with pan-seared chicken, pesto and cherry tomatoes.',
    moodTags: ['energetic', 'happy'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '100', unit: 'g' },
      { name: 'chicken breast', category: 'meat', amount: '160', unit: 'g' },
      { name: 'pesto', category: 'condiment', amount: '2', unit: 'tbsp' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '80', unit: 'g' },
    ],
  },
  {
    title: 'Mac & Cheese with Broccoli',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 3.5,
    calories: 560, proteinG: 24, fatG: 24, carbsG: 62,
    steps: 'Make a light cheese sauce with milk and cheddar, fold in pasta and steamed broccoli.',
    moodTags: ['cozy', 'happy'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '110', unit: 'g' },
      { name: 'cheddar cheese', category: 'dairy', amount: '60', unit: 'g' },
      { name: 'milk', category: 'dairy', amount: '150', unit: 'ml' },
      { name: 'broccoli', category: 'vegetable', amount: '100', unit: 'g' },
    ],
  },

  // ─── Beans, lentils, chickpeas ──────────────────────────────────────────────
  {
    title: 'Three-Bean Chili',
    cookingTimeMin: 35, difficulty: 'easy', estimatedCost: 3.5,
    calories: 420, proteinG: 22, fatG: 8, carbsG: 70,
    steps: 'Simmer mixed beans with tomato, onion, bell pepper and chili spices until thick.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'black beans', category: 'legume', amount: '120', unit: 'g' },
      { name: 'beans', category: 'legume', amount: '120', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Falafel Bowl',
    cookingTimeMin: 30, difficulty: 'medium', estimatedCost: 4.0,
    calories: 460, proteinG: 18, fatG: 18, carbsG: 58,
    steps: 'Blend chickpeas with garlic and herbs, shape and bake, serve with cucumber, tomato and tahini.',
    moodTags: ['happy', 'energetic', 'calm'],
    ingredients: [
      { name: 'chickpeas', category: 'legume', amount: '200', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'tahini', category: 'condiment', amount: '1', unit: 'tbsp' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'White Bean Tomato Stew',
    cookingTimeMin: 28, difficulty: 'easy', estimatedCost: 3.0,
    calories: 380, proteinG: 18, fatG: 9, carbsG: 60,
    steps: 'Simmer white beans with canned tomato, garlic, spinach and olive oil until rich.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'beans', category: 'legume', amount: '200', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Red Lentil Curry',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 3.0,
    calories: 410, proteinG: 20, fatG: 12, carbsG: 58,
    steps: 'Cook red lentils with onion, garlic, tomato and curry spices, finish with coconut milk.',
    moodTags: ['cozy', 'calm', 'energetic'],
    ingredients: [
      { name: 'red lentils', category: 'legume', amount: '150', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '150', unit: 'g' },
      { name: 'coconut milk', category: 'dairy-free', amount: '100', unit: 'ml' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Chickpea Tuna Salad',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 3.5,
    calories: 380, proteinG: 32, fatG: 12, carbsG: 36,
    steps: 'Mix chickpeas and canned tuna with red onion, lemon and olive oil.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'chickpeas', category: 'legume', amount: '150', unit: 'g' },
      { name: 'canned tuna', category: 'fish', amount: '1', unit: 'can' },
      { name: 'onion', category: 'vegetable', amount: '0.25', unit: 'pc' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Black Bean Soup',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 2.5,
    calories: 340, proteinG: 18, fatG: 6, carbsG: 56,
    steps: 'Simmer black beans with onion, garlic and cumin, blend half for a creamy texture.',
    moodTags: ['cozy', 'calm'],
    ingredients: [
      { name: 'black beans', category: 'legume', amount: '200', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
      { name: 'cumin', category: 'spice', amount: '1', unit: 'tsp' },
    ],
  },
  {
    title: 'Spiced Chickpea Wrap',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 3.0,
    calories: 410, proteinG: 16, fatG: 14, carbsG: 56,
    steps: 'Pan-toast chickpeas with paprika and cumin, wrap in a tortilla with greens and yogurt.',
    moodTags: ['happy', 'energetic'],
    ingredients: [
      { name: 'chickpeas', category: 'legume', amount: '150', unit: 'g' },
      { name: 'flour tortilla', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'greek yogurt', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'mixed greens', category: 'vegetable', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Lentil Shepherd-Style Pie',
    cookingTimeMin: 45, difficulty: 'medium', estimatedCost: 4.0,
    calories: 470, proteinG: 22, fatG: 12, carbsG: 70,
    steps: 'Simmer lentils with vegetables, top with mashed potato and bake until golden.',
    moodTags: ['cozy', 'happy', 'calm'],
    ingredients: [
      { name: 'red lentils', category: 'legume', amount: '150', unit: 'g' },
      { name: 'potato', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'green peas', category: 'vegetable', amount: '50', unit: 'g' },
    ],
  },

  // ─── Oats, yogurt, breakfast ────────────────────────────────────────────────
  {
    title: 'Apple Cinnamon Oatmeal',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 2.0,
    calories: 320, proteinG: 10, fatG: 7, carbsG: 56,
    steps: 'Cook oats with milk, stir in grated apple and cinnamon, top with a few nuts.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'rolled oats', category: 'grain', amount: '60', unit: 'g' },
      { name: 'milk', category: 'dairy', amount: '200', unit: 'ml' },
      { name: 'apple', category: 'fruit', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Berry Protein Smoothie',
    cookingTimeMin: 5, difficulty: 'easy', estimatedCost: 3.0,
    calories: 300, proteinG: 24, fatG: 6, carbsG: 40,
    steps: 'Blend Greek yogurt, frozen berries, banana and milk until smooth.',
    moodTags: ['energetic', 'happy', 'focused'],
    ingredients: [
      { name: 'greek yogurt', category: 'dairy', amount: '150', unit: 'g' },
      { name: 'berries', category: 'fruit', amount: '80', unit: 'g' },
      { name: 'banana', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'milk', category: 'dairy', amount: '150', unit: 'ml' },
    ],
  },
  {
    title: 'Peanut Banana Toast',
    cookingTimeMin: 6, difficulty: 'easy', estimatedCost: 2.0,
    calories: 360, proteinG: 14, fatG: 14, carbsG: 48,
    steps: 'Spread peanut butter on wholegrain toast, top with banana slices.',
    moodTags: ['energetic', 'happy', 'cozy'],
    ingredients: [
      { name: 'whole wheat bread', category: 'grain', amount: '2', unit: 'slices' },
      { name: 'peanut butter', category: 'nuts', amount: '1', unit: 'tbsp' },
      { name: 'banana', category: 'fruit', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Chia Pudding',
    cookingTimeMin: 5, difficulty: 'easy', estimatedCost: 2.5,
    calories: 280, proteinG: 10, fatG: 14, carbsG: 32,
    steps: 'Stir chia seeds into milk, refrigerate overnight, top with berries.',
    moodTags: ['calm', 'focused'],
    ingredients: [
      { name: 'chia seeds', category: 'seeds', amount: '30', unit: 'g' },
      { name: 'milk', category: 'dairy', amount: '200', unit: 'ml' },
      { name: 'berries', category: 'fruit', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Savory Yogurt Breakfast Bowl',
    cookingTimeMin: 7, difficulty: 'easy', estimatedCost: 3.0,
    calories: 260, proteinG: 22, fatG: 10, carbsG: 18,
    steps: 'Top Greek yogurt with cucumber, cherry tomato, olive oil and a boiled egg.',
    moodTags: ['focused', 'calm', 'energetic'],
    ingredients: [
      { name: 'greek yogurt', category: 'dairy', amount: '150', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Banana Oat Muffins',
    cookingTimeMin: 25, difficulty: 'medium', estimatedCost: 2.5,
    calories: 300, proteinG: 10, fatG: 8, carbsG: 50,
    steps: 'Mash banana with eggs and oats, spoon into a muffin tin and bake at 180°C for 20 minutes.',
    moodTags: ['happy', 'cozy'],
    ingredients: [
      { name: 'banana', category: 'fruit', amount: '2', unit: 'pcs' },
      { name: 'rolled oats', category: 'grain', amount: '100', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
    ],
  },
  {
    title: 'Cottage Cheese Pancakes',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 3.0,
    calories: 340, proteinG: 28, fatG: 12, carbsG: 30,
    steps: 'Blend cottage cheese, eggs and oats into a batter, cook small pancakes until golden.',
    moodTags: ['energetic', 'happy', 'focused'],
    ingredients: [
      { name: 'cottage cheese', category: 'dairy', amount: '150', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'rolled oats', category: 'grain', amount: '50', unit: 'g' },
    ],
  },
  {
    title: 'Muesli with Yogurt & Fruit',
    cookingTimeMin: 5, difficulty: 'easy', estimatedCost: 2.5,
    calories: 330, proteinG: 16, fatG: 8, carbsG: 52,
    steps: 'Combine muesli with Greek yogurt, top with apple and a drizzle of honey.',
    moodTags: ['calm', 'happy', 'energetic'],
    ingredients: [
      { name: 'muesli', category: 'grain', amount: '60', unit: 'g' },
      { name: 'greek yogurt', category: 'dairy', amount: '150', unit: 'g' },
      { name: 'apple', category: 'fruit', amount: '1', unit: 'pc' },
    ],
  },

  // ─── Fish / tuna / salmon ───────────────────────────────────────────────────
  {
    title: 'Tuna Melt',
    cookingTimeMin: 12, difficulty: 'easy', estimatedCost: 3.5,
    calories: 420, proteinG: 32, fatG: 18, carbsG: 32,
    steps: 'Mix tuna with yogurt and corn, pile on bread, top with cheese and grill until melted.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'canned tuna', category: 'fish', amount: '1', unit: 'can' },
      { name: 'whole wheat bread', category: 'grain', amount: '2', unit: 'slices' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'sweet corn', category: 'vegetable', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Teriyaki Salmon Bowl',
    cookingTimeMin: 25, difficulty: 'medium', estimatedCost: 8.0,
    calories: 520, proteinG: 42, fatG: 22, carbsG: 40,
    steps: 'Glaze salmon with soy and honey, bake, serve over rice with steamed broccoli.',
    moodTags: ['focused', 'energetic'],
    ingredients: [
      { name: 'salmon', category: 'fish', amount: '180', unit: 'g' },
      { name: 'white rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'broccoli', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
      { name: 'honey', category: 'sweetener', amount: '1', unit: 'tsp' },
    ],
  },
  {
    title: 'Garlic Butter Shrimp & Rice',
    cookingTimeMin: 20, difficulty: 'easy', estimatedCost: 7.0,
    calories: 450, proteinG: 34, fatG: 14, carbsG: 48,
    steps: 'Sauté shrimp in garlic, serve over rice with a squeeze of lemon and parsley.',
    moodTags: ['energetic', 'happy', 'focused'],
    ingredients: [
      { name: 'shrimp', category: 'fish', amount: '180', unit: 'g' },
      { name: 'white rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '3', unit: 'cloves' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Mediterranean Baked Fish',
    cookingTimeMin: 30, difficulty: 'medium', estimatedCost: 6.5,
    calories: 380, proteinG: 40, fatG: 14, carbsG: 18,
    steps: 'Bake white fish with cherry tomatoes, olives, garlic and olive oil at 200°C.',
    moodTags: ['focused', 'calm'],
    ingredients: [
      { name: 'white fish', category: 'fish', amount: '200', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Salmon & Avocado Salad',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 8.0,
    calories: 460, proteinG: 36, fatG: 30, carbsG: 12,
    steps: 'Flake cooked salmon over mixed greens with avocado, cucumber and a lemon dressing.',
    moodTags: ['energetic', 'focused', 'calm'],
    ingredients: [
      { name: 'salmon', category: 'fish', amount: '160', unit: 'g' },
      { name: 'avocado', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'mixed greens', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Tuna Stuffed Bell Peppers',
    cookingTimeMin: 28, difficulty: 'easy', estimatedCost: 4.0,
    calories: 360, proteinG: 30, fatG: 12, carbsG: 34,
    steps: 'Mix tuna with cooked rice and corn, stuff into halved peppers, bake with cheese on top.',
    moodTags: ['cozy', 'focused', 'happy'],
    ingredients: [
      { name: 'canned tuna', category: 'fish', amount: '1', unit: 'can' },
      { name: 'bell pepper', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'white rice', category: 'grain', amount: '60', unit: 'g' },
      { name: 'cheese', category: 'dairy', amount: '30', unit: 'g' },
    ],
  },

  // ─── Vegetable-forward, soups, salads ───────────────────────────────────────
  {
    title: 'Minestrone Soup',
    cookingTimeMin: 35, difficulty: 'easy', estimatedCost: 3.0,
    calories: 320, proteinG: 14, fatG: 8, carbsG: 52,
    steps: 'Simmer beans, pasta and mixed vegetables in a tomato broth until tender.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'beans', category: 'legume', amount: '120', unit: 'g' },
      { name: 'pasta', category: 'grain', amount: '50', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '150', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Roasted Vegetable Traybake',
    cookingTimeMin: 35, difficulty: 'easy', estimatedCost: 3.5,
    calories: 300, proteinG: 8, fatG: 14, carbsG: 40,
    steps: 'Toss potato, bell pepper, zucchini and onion with olive oil, roast at 200°C until caramelised.',
    moodTags: ['cozy', 'happy', 'calm'],
    ingredients: [
      { name: 'potato', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'zucchini', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '2', unit: 'tbsp' },
    ],
  },
  {
    title: 'Creamy Tomato Soup',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 2.5,
    calories: 240, proteinG: 8, fatG: 12, carbsG: 28,
    steps: 'Simmer canned tomatoes with onion and garlic, blend smooth and stir in a splash of milk.',
    moodTags: ['cozy', 'calm'],
    ingredients: [
      { name: 'canned tomatoes', category: 'vegetable', amount: '300', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
      { name: 'milk', category: 'dairy', amount: '100', unit: 'ml' },
    ],
  },
  {
    title: 'Greek Salad',
    cookingTimeMin: 12, difficulty: 'easy', estimatedCost: 3.5,
    calories: 280, proteinG: 10, fatG: 20, carbsG: 16,
    steps: 'Combine cucumber, tomato, onion and feta, dress with olive oil and oregano.',
    moodTags: ['happy', 'calm', 'energetic'],
    ingredients: [
      { name: 'cucumber', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '120', unit: 'g' },
      { name: 'feta', category: 'dairy', amount: '50', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '0.25', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Carrot Ginger Soup',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 2.5,
    calories: 220, proteinG: 5, fatG: 9, carbsG: 32,
    steps: 'Simmer carrot and onion with ginger and broth, blend until silky.',
    moodTags: ['calm', 'cozy', 'focused'],
    ingredients: [
      { name: 'carrot', category: 'vegetable', amount: '4', unit: 'pcs' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'ginger', category: 'spice', amount: '1', unit: 'tsp' },
      { name: 'vegetable broth', category: 'liquid', amount: '500', unit: 'ml' },
    ],
  },
  {
    title: 'Stuffed Zucchini Boats',
    cookingTimeMin: 35, difficulty: 'medium', estimatedCost: 4.0,
    calories: 320, proteinG: 22, fatG: 16, carbsG: 22,
    steps: 'Hollow zucchini, fill with spiced ground turkey and tomato, bake with cheese until bubbling.',
    moodTags: ['cozy', 'focused', 'happy'],
    ingredients: [
      { name: 'zucchini', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'ground turkey', category: 'meat', amount: '150', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Cabbage Stir-Fry',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 2.5,
    calories: 200, proteinG: 8, fatG: 10, carbsG: 22,
    steps: 'Stir-fry shredded cabbage and carrot with garlic and soy sauce until just tender.',
    moodTags: ['calm', 'energetic'],
    ingredients: [
      { name: 'cabbage', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Caprese Salad',
    cookingTimeMin: 8, difficulty: 'easy', estimatedCost: 4.0,
    calories: 300, proteinG: 16, fatG: 22, carbsG: 10,
    steps: 'Layer sliced tomato and mozzarella, drizzle olive oil and scatter basil.',
    moodTags: ['happy', 'calm'],
    ingredients: [
      { name: 'cherry tomatoes', category: 'vegetable', amount: '150', unit: 'g' },
      { name: 'mozzarella', category: 'dairy', amount: '80', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Potato Leek Soup',
    cookingTimeMin: 35, difficulty: 'easy', estimatedCost: 2.5,
    calories: 280, proteinG: 8, fatG: 10, carbsG: 44,
    steps: 'Simmer potato and leek in broth, blend smooth and finish with a little milk.',
    moodTags: ['cozy', 'calm'],
    ingredients: [
      { name: 'potato', category: 'vegetable', amount: '3', unit: 'pcs' },
      { name: 'leek', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'vegetable broth', category: 'liquid', amount: '500', unit: 'ml' },
      { name: 'milk', category: 'dairy', amount: '80', unit: 'ml' },
    ],
  },
  {
    title: 'Broccoli Cheddar Soup',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 3.5,
    calories: 320, proteinG: 16, fatG: 20, carbsG: 22,
    steps: 'Simmer broccoli with onion and broth, blend lightly and stir in cheddar.',
    moodTags: ['cozy', 'happy', 'calm'],
    ingredients: [
      { name: 'broccoli', category: 'vegetable', amount: '250', unit: 'g' },
      { name: 'cheddar cheese', category: 'dairy', amount: '60', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'vegetable broth', category: 'liquid', amount: '400', unit: 'ml' },
    ],
  },

  // ─── Tofu, beef, turkey, misc protein ───────────────────────────────────────
  {
    title: 'Crispy Tofu Rice Bowl',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 4.0,
    calories: 440, proteinG: 24, fatG: 18, carbsG: 46,
    steps: 'Coat tofu in cornstarch and pan-fry until crisp, serve over rice with broccoli and soy glaze.',
    moodTags: ['energetic', 'calm', 'focused'],
    ingredients: [
      { name: 'tofu', category: 'soy', amount: '200', unit: 'g' },
      { name: 'white rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'broccoli', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Tofu Scramble',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 3.0,
    calories: 300, proteinG: 22, fatG: 18, carbsG: 12,
    steps: 'Crumble tofu, sauté with turmeric, bell pepper and spinach until hot.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'tofu', category: 'soy', amount: '200', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'spinach', category: 'vegetable', amount: '50', unit: 'g' },
      { name: 'turmeric', category: 'spice', amount: '0.5', unit: 'tsp' },
    ],
  },
  {
    title: 'Beef & Broccoli',
    cookingTimeMin: 25, difficulty: 'medium', estimatedCost: 6.5,
    calories: 520, proteinG: 40, fatG: 24, carbsG: 34,
    steps: 'Stir-fry sliced beef with broccoli in a garlic-soy sauce, serve over rice.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'beef', category: 'meat', amount: '180', unit: 'g' },
      { name: 'broccoli', category: 'vegetable', amount: '150', unit: 'g' },
      { name: 'white rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'soy sauce', category: 'condiment', amount: '2', unit: 'tbsp' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Turkey Chili',
    cookingTimeMin: 35, difficulty: 'easy', estimatedCost: 5.0,
    calories: 440, proteinG: 36, fatG: 14, carbsG: 44,
    steps: 'Brown ground turkey, simmer with beans, tomato, onion and chili spices.',
    moodTags: ['cozy', 'energetic', 'happy'],
    ingredients: [
      { name: 'ground turkey', category: 'meat', amount: '200', unit: 'g' },
      { name: 'beans', category: 'legume', amount: '150', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Beef Stuffed Peppers',
    cookingTimeMin: 40, difficulty: 'medium', estimatedCost: 5.5,
    calories: 480, proteinG: 32, fatG: 22, carbsG: 38,
    steps: 'Fill halved peppers with seasoned beef and rice, bake until tender, top with cheese.',
    moodTags: ['cozy', 'happy'],
    ingredients: [
      { name: 'ground beef', category: 'meat', amount: '200', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'white rice', category: 'grain', amount: '60', unit: 'g' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Turkey Meatballs in Tomato Sauce',
    cookingTimeMin: 30, difficulty: 'medium', estimatedCost: 5.0,
    calories: 420, proteinG: 36, fatG: 18, carbsG: 28,
    steps: 'Roll seasoned turkey into meatballs, brown, then simmer in tomato sauce, serve over pasta.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'ground turkey', category: 'meat', amount: '200', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'pasta', category: 'grain', amount: '80', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Edamame Veggie Stir-Fry',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 4.0,
    calories: 360, proteinG: 22, fatG: 14, carbsG: 40,
    steps: 'Stir-fry edamame with bell pepper, carrot and noodles in a light soy sauce.',
    moodTags: ['energetic', 'happy', 'focused'],
    ingredients: [
      { name: 'edamame', category: 'soy', amount: '120', unit: 'g' },
      { name: 'noodles', category: 'grain', amount: '80', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Tofu Miso Noodle Soup',
    cookingTimeMin: 20, difficulty: 'easy', estimatedCost: 3.5,
    calories: 360, proteinG: 20, fatG: 10, carbsG: 48,
    steps: 'Simmer broth with miso, add noodles, tofu and green onion.',
    moodTags: ['cozy', 'calm'],
    ingredients: [
      { name: 'tofu', category: 'soy', amount: '150', unit: 'g' },
      { name: 'noodles', category: 'grain', amount: '80', unit: 'g' },
      { name: 'miso paste', category: 'soy', amount: '2', unit: 'tbsp' },
      { name: 'green onion', category: 'vegetable', amount: '2', unit: 'pcs' },
    ],
  },

  // ─── Snacks / light / quick ─────────────────────────────────────────────────
  {
    title: 'Hummus & Veggie Plate',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 3.0,
    calories: 320, proteinG: 12, fatG: 18, carbsG: 32,
    steps: 'Serve hummus with carrot sticks, cucumber, bell pepper and wholegrain pita.',
    moodTags: ['calm', 'happy', 'focused'],
    ingredients: [
      { name: 'hummus', category: 'legume', amount: '100', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Caprese Avocado Toast',
    cookingTimeMin: 8, difficulty: 'easy', estimatedCost: 3.5,
    calories: 360, proteinG: 12, fatG: 22, carbsG: 32,
    steps: 'Mash avocado on toast, top with sliced tomato and mozzarella.',
    moodTags: ['happy', 'calm', 'energetic'],
    ingredients: [
      { name: 'whole wheat bread', category: 'grain', amount: '2', unit: 'slices' },
      { name: 'avocado', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'mozzarella', category: 'dairy', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Apple Peanut Butter Snack',
    cookingTimeMin: 5, difficulty: 'easy', estimatedCost: 2.0,
    calories: 260, proteinG: 8, fatG: 14, carbsG: 30,
    steps: 'Slice apple and serve with a spoon of peanut butter for dipping.',
    moodTags: ['happy', 'energetic', 'calm'],
    ingredients: [
      { name: 'apple', category: 'fruit', amount: '1', unit: 'pc' },
      { name: 'peanut butter', category: 'nuts', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Yogurt Nut Bowl',
    cookingTimeMin: 5, difficulty: 'easy', estimatedCost: 2.5,
    calories: 300, proteinG: 18, fatG: 14, carbsG: 26,
    steps: 'Top Greek yogurt with mixed nuts, banana and a sprinkle of seeds.',
    moodTags: ['calm', 'focused', 'happy'],
    ingredients: [
      { name: 'greek yogurt', category: 'dairy', amount: '170', unit: 'g' },
      { name: 'almonds', category: 'nuts', amount: '20', unit: 'g' },
      { name: 'banana', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'pumpkin seeds', category: 'seeds', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Caprese Pasta Salad',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 3.5,
    calories: 440, proteinG: 16, fatG: 16, carbsG: 60,
    steps: 'Toss cooled pasta with cherry tomato, mozzarella, basil and olive oil.',
    moodTags: ['happy', 'calm', 'energetic'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '100', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'mozzarella', category: 'dairy', amount: '60', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Cucumber Tuna Boats',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 3.0,
    calories: 240, proteinG: 26, fatG: 9, carbsG: 10,
    steps: 'Halve cucumbers, scoop centres, fill with tuna mixed with yogurt and corn.',
    moodTags: ['focused', 'energetic', 'calm'],
    ingredients: [
      { name: 'cucumber', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'canned tuna', category: 'fish', amount: '1', unit: 'can' },
      { name: 'greek yogurt', category: 'dairy', amount: '30', unit: 'g' },
      { name: 'sweet corn', category: 'vegetable', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Baked Sweet Potato with Beans',
    cookingTimeMin: 45, difficulty: 'easy', estimatedCost: 3.0,
    calories: 420, proteinG: 16, fatG: 8, carbsG: 76,
    steps: 'Bake sweet potato whole, split and top with spiced black beans and yogurt.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'sweet potato', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'black beans', category: 'legume', amount: '150', unit: 'g' },
      { name: 'greek yogurt', category: 'dairy', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Veggie Pita Pocket',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 3.0,
    calories: 360, proteinG: 14, fatG: 12, carbsG: 52,
    steps: 'Fill a wholegrain pita with hummus, cucumber, tomato, lettuce and feta.',
    moodTags: ['happy', 'calm', 'energetic'],
    ingredients: [
      { name: 'pita bread', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'hummus', category: 'legume', amount: '60', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '50', unit: 'g' },
      { name: 'feta', category: 'dairy', amount: '30', unit: 'g' },
    ],
  },
  {
    title: 'Oatmeal Banana Bowl',
    cookingTimeMin: 8, difficulty: 'easy', estimatedCost: 1.5,
    calories: 310, proteinG: 10, fatG: 6, carbsG: 58,
    steps: 'Cook oats with water and milk, top with banana and a drizzle of honey.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'rolled oats', category: 'grain', amount: '60', unit: 'g' },
      { name: 'milk', category: 'dairy', amount: '150', unit: 'ml' },
      { name: 'banana', category: 'fruit', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Caprese Stuffed Chicken',
    cookingTimeMin: 35, difficulty: 'medium', estimatedCost: 6.5,
    calories: 460, proteinG: 48, fatG: 22, carbsG: 8,
    steps: 'Stuff chicken breast with tomato and mozzarella, bake until cooked through.',
    moodTags: ['focused', 'energetic'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '200', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'mozzarella', category: 'dairy', amount: '50', unit: 'g' },
    ],
  },
  {
    title: 'Spinach & Cheese Quesadilla',
    cookingTimeMin: 12, difficulty: 'easy', estimatedCost: 3.0,
    calories: 420, proteinG: 18, fatG: 20, carbsG: 44,
    steps: 'Fill a tortilla with cheese and wilted spinach, toast until golden and melty.',
    moodTags: ['cozy', 'happy', 'calm'],
    ingredients: [
      { name: 'flour tortilla', category: 'grain', amount: '2', unit: 'pcs' },
      { name: 'cheese', category: 'dairy', amount: '60', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Veggie Omelette Wrap',
    cookingTimeMin: 12, difficulty: 'easy', estimatedCost: 3.0,
    calories: 380, proteinG: 22, fatG: 18, carbsG: 32,
    steps: 'Make a thin omelette with bell pepper and onion, roll in a tortilla with greens.',
    moodTags: ['energetic', 'focused', 'happy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'flour tortilla', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '0.25', unit: 'pc' },
    ],
  },
  {
    title: 'Lentil Salad with Feta',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 3.5,
    calories: 400, proteinG: 22, fatG: 16, carbsG: 44,
    steps: 'Toss cooked lentils with cucumber, tomato, feta, lemon and olive oil.',
    moodTags: ['calm', 'focused', 'happy'],
    ingredients: [
      { name: 'red lentils', category: 'legume', amount: '120', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'feta', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Cauliflower Rice Stir-Fry',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 3.5,
    calories: 260, proteinG: 14, fatG: 12, carbsG: 24,
    steps: 'Pulse cauliflower into rice, stir-fry with egg, peas and carrot in soy sauce.',
    moodTags: ['energetic', 'focused', 'calm'],
    ingredients: [
      { name: 'cauliflower', category: 'vegetable', amount: '250', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'green peas', category: 'vegetable', amount: '50', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Baked Cod with Potatoes',
    cookingTimeMin: 35, difficulty: 'medium', estimatedCost: 6.0,
    calories: 400, proteinG: 38, fatG: 12, carbsG: 38,
    steps: 'Roast cod with potato slices, garlic, lemon and olive oil at 200°C.',
    moodTags: ['focused', 'calm'],
    ingredients: [
      { name: 'white fish', category: 'fish', amount: '200', unit: 'g' },
      { name: 'potato', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Chicken Avocado Wrap',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 5.0,
    calories: 470, proteinG: 36, fatG: 20, carbsG: 36,
    steps: 'Fill a tortilla with sliced chicken, avocado, lettuce and a yogurt dressing.',
    moodTags: ['energetic', 'happy', 'focused'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '150', unit: 'g' },
      { name: 'flour tortilla', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'avocado', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'lettuce', category: 'vegetable', amount: '30', unit: 'g' },
    ],
  },
  {
    title: 'Vegetable Barley Soup',
    cookingTimeMin: 40, difficulty: 'easy', estimatedCost: 3.0,
    calories: 320, proteinG: 12, fatG: 6, carbsG: 60,
    steps: 'Simmer barley with carrot, celery, onion and tomato until thick and hearty.',
    moodTags: ['cozy', 'calm', 'focused'],
    ingredients: [
      { name: 'barley', category: 'grain', amount: '80', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '150', unit: 'g' },
    ],
  },
  {
    title: 'Peanut Tofu Noodles',
    cookingTimeMin: 22, difficulty: 'medium', estimatedCost: 4.5,
    calories: 520, proteinG: 26, fatG: 22, carbsG: 56,
    steps: 'Toss noodles and pan-fried tofu in a peanut-soy sauce with carrot and green onion.',
    moodTags: ['energetic', 'happy', 'cozy'],
    ingredients: [
      { name: 'tofu', category: 'soy', amount: '150', unit: 'g' },
      { name: 'noodles', category: 'grain', amount: '100', unit: 'g' },
      { name: 'peanut butter', category: 'nuts', amount: '1', unit: 'tbsp' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Egg & Avocado Rice Bowl',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 3.5,
    calories: 460, proteinG: 18, fatG: 22, carbsG: 48,
    steps: 'Top warm rice with a soft-boiled egg, sliced avocado, soy sauce and green onion.',
    moodTags: ['calm', 'focused', 'happy'],
    ingredients: [
      { name: 'white rice', category: 'grain', amount: '120', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'avocado', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'green onion', category: 'vegetable', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Roasted Chickpea Salad Bowl',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 3.5,
    calories: 420, proteinG: 18, fatG: 16, carbsG: 52,
    steps: 'Roast spiced chickpeas, serve over greens with cucumber, tomato and tahini.',
    moodTags: ['energetic', 'focused', 'calm'],
    ingredients: [
      { name: 'chickpeas', category: 'legume', amount: '200', unit: 'g' },
      { name: 'mixed greens', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'tahini', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Turkey Avocado Sandwich',
    cookingTimeMin: 10, difficulty: 'easy', estimatedCost: 4.5,
    calories: 420, proteinG: 32, fatG: 18, carbsG: 36,
    steps: 'Layer sliced turkey, avocado, lettuce and tomato between wholegrain bread.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'turkey breast', category: 'meat', amount: '120', unit: 'g' },
      { name: 'whole wheat bread', category: 'grain', amount: '2', unit: 'slices' },
      { name: 'avocado', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'lettuce', category: 'vegetable', amount: '20', unit: 'g' },
    ],
  },
  {
    title: 'Spinach Mushroom Quinoa',
    cookingTimeMin: 25, difficulty: 'easy', estimatedCost: 4.0,
    calories: 400, proteinG: 16, fatG: 14, carbsG: 54,
    steps: 'Cook quinoa, fold in sautéed mushrooms, spinach and garlic.',
    moodTags: ['focused', 'calm', 'energetic'],
    ingredients: [
      { name: 'quinoa', category: 'grain', amount: '80', unit: 'g' },
      { name: 'mushrooms', category: 'vegetable', amount: '120', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Banana Berry Smoothie Bowl',
    cookingTimeMin: 8, difficulty: 'easy', estimatedCost: 3.0,
    calories: 320, proteinG: 14, fatG: 8, carbsG: 52,
    steps: 'Blend banana, berries and yogurt thick, pour into a bowl and top with oats and seeds.',
    moodTags: ['happy', 'energetic', 'calm'],
    ingredients: [
      { name: 'banana', category: 'fruit', amount: '1', unit: 'pc' },
      { name: 'berries', category: 'fruit', amount: '80', unit: 'g' },
      { name: 'greek yogurt', category: 'dairy', amount: '120', unit: 'g' },
      { name: 'rolled oats', category: 'grain', amount: '20', unit: 'g' },
    ],
  },
  {
    title: 'Vegetable Egg Drop Ramen',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 3.5,
    calories: 420, proteinG: 18, fatG: 12, carbsG: 60,
    steps: 'Simmer broth with vegetables, add ramen noodles and swirl in a beaten egg.',
    moodTags: ['cozy', 'happy', 'calm'],
    ingredients: [
      { name: 'ramen noodles', category: 'grain', amount: '100', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '1', unit: 'pc' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'green onion', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Cheesy Broccoli Baked Potato',
    cookingTimeMin: 45, difficulty: 'easy', estimatedCost: 3.0,
    calories: 420, proteinG: 18, fatG: 16, carbsG: 56,
    steps: 'Bake a potato, split and fill with steamed broccoli and melted cheddar.',
    moodTags: ['cozy', 'happy'],
    ingredients: [
      { name: 'potato', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'broccoli', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'cheddar cheese', category: 'dairy', amount: '50', unit: 'g' },
    ],
  },
  {
    title: 'Shrimp Avocado Salad',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 7.0,
    calories: 340, proteinG: 30, fatG: 18, carbsG: 14,
    steps: 'Toss cooked shrimp with avocado, cucumber, tomato and a lime dressing.',
    moodTags: ['energetic', 'focused', 'calm'],
    ingredients: [
      { name: 'shrimp', category: 'fish', amount: '160', unit: 'g' },
      { name: 'avocado', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Pumpkin Lentil Soup',
    cookingTimeMin: 35, difficulty: 'easy', estimatedCost: 3.0,
    calories: 340, proteinG: 16, fatG: 8, carbsG: 54,
    steps: 'Simmer pumpkin and red lentils with onion and broth, blend until smooth.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'pumpkin', category: 'vegetable', amount: '250', unit: 'g' },
      { name: 'red lentils', category: 'legume', amount: '100', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'vegetable broth', category: 'liquid', amount: '500', unit: 'ml' },
    ],
  },
  {
    title: 'Cheese & Tomato Pasta Bake',
    cookingTimeMin: 35, difficulty: 'medium', estimatedCost: 4.0,
    calories: 540, proteinG: 22, fatG: 20, carbsG: 70,
    steps: 'Mix cooked pasta with tomato sauce, top with cheese and bake until bubbling.',
    moodTags: ['cozy', 'happy'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '120', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'cheese', category: 'dairy', amount: '60', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Chicken & Chickpea Stew',
    cookingTimeMin: 35, difficulty: 'medium', estimatedCost: 5.5,
    calories: 480, proteinG: 42, fatG: 16, carbsG: 42,
    steps: 'Brown chicken, simmer with chickpeas, tomato, onion and warming spices.',
    moodTags: ['cozy', 'focused', 'energetic'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '180', unit: 'g' },
      { name: 'chickpeas', category: 'legume', amount: '150', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '150', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Veggie Rice Paper Rolls',
    cookingTimeMin: 25, difficulty: 'medium', estimatedCost: 4.0,
    calories: 280, proteinG: 14, fatG: 8, carbsG: 42,
    steps: 'Wrap rice paper around carrot, cucumber, tofu and herbs, serve with peanut dip.',
    moodTags: ['calm', 'happy', 'focused'],
    ingredients: [
      { name: 'rice paper', category: 'grain', amount: '6', unit: 'sheets' },
      { name: 'tofu', category: 'soy', amount: '100', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Baked Feta Tomato Pasta',
    cookingTimeMin: 35, difficulty: 'easy', estimatedCost: 4.5,
    calories: 560, proteinG: 20, fatG: 22, carbsG: 70,
    steps: 'Bake feta with cherry tomatoes and garlic, mash into a sauce and toss with pasta.',
    moodTags: ['cozy', 'happy', 'calm'],
    ingredients: [
      { name: 'pasta', category: 'grain', amount: '120', unit: 'g' },
      { name: 'feta', category: 'dairy', amount: '80', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '150', unit: 'g' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Turkey Vegetable Skillet',
    cookingTimeMin: 22, difficulty: 'easy', estimatedCost: 5.0,
    calories: 400, proteinG: 36, fatG: 16, carbsG: 28,
    steps: 'Brown ground turkey with zucchini, bell pepper and tomato in one pan.',
    moodTags: ['energetic', 'focused', 'cozy'],
    ingredients: [
      { name: 'ground turkey', category: 'meat', amount: '200', unit: 'g' },
      { name: 'zucchini', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '100', unit: 'g' },
    ],
  },
  {
    title: 'Oat & Yogurt Breakfast Jar',
    cookingTimeMin: 5, difficulty: 'easy', estimatedCost: 2.5,
    calories: 340, proteinG: 18, fatG: 8, carbsG: 50,
    steps: 'Layer oats, Greek yogurt and berries in a jar, chill and eat cold.',
    moodTags: ['calm', 'happy', 'focused'],
    ingredients: [
      { name: 'rolled oats', category: 'grain', amount: '50', unit: 'g' },
      { name: 'greek yogurt', category: 'dairy', amount: '150', unit: 'g' },
      { name: 'berries', category: 'fruit', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Bean & Cheese Burrito',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 3.0,
    calories: 480, proteinG: 20, fatG: 16, carbsG: 66,
    steps: 'Warm refried beans, fill a tortilla with beans, cheese and rice, then roll and toast.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'beans', category: 'legume', amount: '150', unit: 'g' },
      { name: 'flour tortilla', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'white rice', category: 'grain', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Greek Chicken Pita',
    cookingTimeMin: 22, difficulty: 'easy', estimatedCost: 5.0,
    calories: 470, proteinG: 38, fatG: 16, carbsG: 44,
    steps: 'Stuff a pita with grilled chicken, cucumber, tomato and a yogurt-garlic sauce.',
    moodTags: ['energetic', 'happy', 'focused'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '160', unit: 'g' },
      { name: 'pita bread', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'greek yogurt', category: 'dairy', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Spiced Cauliflower & Chickpeas',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 3.5,
    calories: 360, proteinG: 16, fatG: 14, carbsG: 48,
    steps: 'Roast cauliflower and chickpeas with cumin and paprika, finish with lemon and yogurt.',
    moodTags: ['calm', 'energetic', 'focused'],
    ingredients: [
      { name: 'cauliflower', category: 'vegetable', amount: '250', unit: 'g' },
      { name: 'chickpeas', category: 'legume', amount: '150', unit: 'g' },
      { name: 'greek yogurt', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'cumin', category: 'spice', amount: '1', unit: 'tsp' },
    ],
  },
  {
    title: 'Salmon Rice Poke Bowl',
    cookingTimeMin: 20, difficulty: 'medium', estimatedCost: 8.5,
    calories: 500, proteinG: 38, fatG: 20, carbsG: 46,
    steps: 'Top sushi rice with cubed cooked salmon, cucumber, avocado and a soy drizzle.',
    moodTags: ['focused', 'energetic', 'calm'],
    ingredients: [
      { name: 'salmon', category: 'fish', amount: '160', unit: 'g' },
      { name: 'white rice', category: 'grain', amount: '120', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'avocado', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Veggie Chickpea Pancakes',
    cookingTimeMin: 20, difficulty: 'easy', estimatedCost: 3.0,
    calories: 320, proteinG: 16, fatG: 10, carbsG: 42,
    steps: 'Whisk chickpea flour into a batter with grated zucchini and onion, pan-fry savory pancakes.',
    moodTags: ['energetic', 'happy', 'calm'],
    ingredients: [
      { name: 'chickpea flour', category: 'legume', amount: '100', unit: 'g' },
      { name: 'zucchini', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Beef Vegetable Stir-Fry',
    cookingTimeMin: 22, difficulty: 'medium', estimatedCost: 6.0,
    calories: 480, proteinG: 36, fatG: 22, carbsG: 36,
    steps: 'Stir-fry strips of beef with bell pepper, broccoli and onion in a soy-garlic sauce, serve over rice.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'beef', category: 'meat', amount: '180', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'broccoli', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'white rice', category: 'grain', amount: '100', unit: 'g' },
      { name: 'soy sauce', category: 'condiment', amount: '2', unit: 'tbsp' },
    ],
  },
  {
    title: 'Tomato Egg Noodle Soup',
    cookingTimeMin: 18, difficulty: 'easy', estimatedCost: 2.5,
    calories: 360, proteinG: 16, fatG: 10, carbsG: 52,
    steps: 'Simmer tomato in broth, add noodles, swirl in beaten egg and green onion.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'noodles', category: 'grain', amount: '90', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '1', unit: 'pc' },
      { name: 'green onion', category: 'vegetable', amount: '2', unit: 'pcs' },
    ],
  },
  {
    title: 'Yogurt Berry Overnight Oats',
    cookingTimeMin: 5, difficulty: 'easy', estimatedCost: 2.5,
    calories: 350, proteinG: 18, fatG: 8, carbsG: 54,
    steps: 'Mix oats, yogurt and milk, refrigerate overnight, top with berries and seeds.',
    moodTags: ['calm', 'focused', 'happy'],
    ingredients: [
      { name: 'rolled oats', category: 'grain', amount: '50', unit: 'g' },
      { name: 'greek yogurt', category: 'dairy', amount: '120', unit: 'g' },
      { name: 'milk', category: 'dairy', amount: '100', unit: 'ml' },
      { name: 'berries', category: 'fruit', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Chicken Spinach Stuffed Sweet Potato',
    cookingTimeMin: 45, difficulty: 'medium', estimatedCost: 5.0,
    calories: 440, proteinG: 36, fatG: 12, carbsG: 50,
    steps: 'Bake sweet potato, split and fill with shredded chicken and wilted spinach.',
    moodTags: ['focused', 'energetic', 'cozy'],
    ingredients: [
      { name: 'sweet potato', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'chicken breast', category: 'meat', amount: '150', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '50', unit: 'g' },
    ],
  },
  {
    title: 'Caprese Quinoa Bowl',
    cookingTimeMin: 22, difficulty: 'easy', estimatedCost: 4.5,
    calories: 420, proteinG: 18, fatG: 16, carbsG: 50,
    steps: 'Toss cooked quinoa with cherry tomato, mozzarella, basil and olive oil.',
    moodTags: ['happy', 'calm', 'focused'],
    ingredients: [
      { name: 'quinoa', category: 'grain', amount: '80', unit: 'g' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'mozzarella', category: 'dairy', amount: '50', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Vegetable Omelette Rice Bowl',
    cookingTimeMin: 15, difficulty: 'easy', estimatedCost: 3.0,
    calories: 420, proteinG: 18, fatG: 16, carbsG: 50,
    steps: 'Make a vegetable omelette, slice and serve over warm rice with soy sauce.',
    moodTags: ['energetic', 'focused', 'happy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'white rice', category: 'grain', amount: '120', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'green peas', category: 'vegetable', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Lentil & Spinach Soup',
    cookingTimeMin: 30, difficulty: 'easy', estimatedCost: 2.5,
    calories: 320, proteinG: 18, fatG: 7, carbsG: 50,
    steps: 'Simmer red lentils with onion, carrot and garlic, stir in spinach at the end.',
    moodTags: ['cozy', 'calm', 'focused'],
    ingredients: [
      { name: 'red lentils', category: 'legume', amount: '150', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Cheesy Scrambled Egg Burrito',
    cookingTimeMin: 12, difficulty: 'easy', estimatedCost: 3.0,
    calories: 440, proteinG: 22, fatG: 22, carbsG: 38,
    steps: 'Scramble eggs with cheese, wrap in a tortilla with salsa and beans.',
    moodTags: ['energetic', 'happy', 'cozy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'flour tortilla', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'black beans', category: 'legume', amount: '60', unit: 'g' },
      { name: 'salsa', category: 'condiment', amount: '40', unit: 'g' },
    ],
  },
]
