import { PrismaClient } from '@prisma/client'
import { extraRecipes } from './recipes.extra'

const prisma = new PrismaClient()

const baseRecipes = [
  {
    title: 'Banana Oat Smoothie',
    cookingTimeMin: 5,
    difficulty: 'easy',
    estimatedCost: 2.5,
    calories: 320,
    proteinG: 8,
    fatG: 8,
    carbsG: 52,
    steps: 'Blend banana, oats, almond milk, and honey until smooth. Serve cold.',
    moodTags: ['happy', 'energetic', 'calm'],
    ingredients: [
      { name: 'banana', category: 'fruit', amount: '1', unit: 'pc' },
      { name: 'rolled oats', category: 'grain', amount: '50', unit: 'g' },
      { name: 'almond milk', category: 'dairy-free', amount: '200', unit: 'ml' },
      { name: 'honey', category: 'sweetener', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Grilled Chicken Salad',
    cookingTimeMin: 25,
    difficulty: 'easy',
    estimatedCost: 6.0,
    calories: 450,
    proteinG: 42,
    fatG: 18,
    carbsG: 10,
    steps: 'Grill chicken breast, slice and serve over mixed greens with olive oil and lemon dressing.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '200', unit: 'g' },
      { name: 'mixed greens', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '2', unit: 'tbsp' },
      { name: 'lemon', category: 'fruit', amount: '1', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '80', unit: 'g' },
    ],
  },
  {
    title: 'Lentil Dal',
    cookingTimeMin: 35,
    difficulty: 'medium',
    estimatedCost: 3.0,
    calories: 380,
    proteinG: 18,
    fatG: 8,
    carbsG: 58,
    steps: 'Sauté onion and garlic, add lentils, tomatoes, cumin and turmeric. Simmer 25 minutes.',
    moodTags: ['calm', 'cozy', 'happy'],
    ingredients: [
      { name: 'red lentils', category: 'legume', amount: '150', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'garlic', category: 'vegetable', amount: '3', unit: 'cloves' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'cumin', category: 'spice', amount: '1', unit: 'tsp' },
      { name: 'turmeric', category: 'spice', amount: '0.5', unit: 'tsp' },
      { name: 'olive oil', category: 'oil', amount: '2', unit: 'tbsp' },
    ],
  },
  {
    title: 'Avocado Toast with Egg',
    cookingTimeMin: 10,
    difficulty: 'easy',
    estimatedCost: 4.0,
    calories: 410,
    proteinG: 16,
    fatG: 22,
    carbsG: 38,
    steps: 'Toast bread, mash avocado with salt and lemon, top with a fried egg.',
    moodTags: ['energetic', 'focused', 'happy'],
    ingredients: [
      { name: 'whole wheat bread', category: 'grain', amount: '2', unit: 'slices' },
      { name: 'avocado', category: 'fruit', amount: '1', unit: 'pc' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Salmon with Quinoa',
    cookingTimeMin: 30,
    difficulty: 'medium',
    estimatedCost: 9.0,
    calories: 520,
    proteinG: 48,
    fatG: 20,
    carbsG: 28,
    steps: 'Cook quinoa per package. Pan-sear salmon fillet 4 min each side. Serve with steamed broccoli.',
    moodTags: ['focused', 'energetic'],
    ingredients: [
      { name: 'salmon', category: 'fish', amount: '200', unit: 'g' },
      { name: 'quinoa', category: 'grain', amount: '80', unit: 'g' },
      { name: 'broccoli', category: 'vegetable', amount: '150', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Vegetable Stir-Fry with Tofu',
    cookingTimeMin: 20,
    difficulty: 'easy',
    estimatedCost: 4.5,
    calories: 360,
    proteinG: 22,
    fatG: 14,
    carbsG: 28,
    steps: 'Press and cube tofu, stir-fry with mixed vegetables and soy sauce over high heat.',
    moodTags: ['energetic', 'calm'],
    ingredients: [
      { name: 'tofu', category: 'soy', amount: '200', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'broccoli', category: 'vegetable', amount: '100', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'soy sauce', category: 'condiment', amount: '3', unit: 'tbsp' },
      { name: 'sesame oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Greek Yogurt Parfait',
    cookingTimeMin: 5,
    difficulty: 'easy',
    estimatedCost: 3.5,
    calories: 280,
    proteinG: 20,
    fatG: 6,
    carbsG: 36,
    steps: 'Layer Greek yogurt, granola and fresh berries in a glass. Drizzle honey on top.',
    moodTags: ['happy', 'calm', 'cozy'],
    ingredients: [
      { name: 'greek yogurt', category: 'dairy', amount: '200', unit: 'g' },
      { name: 'granola', category: 'grain', amount: '50', unit: 'g' },
      { name: 'blueberries', category: 'fruit', amount: '80', unit: 'g' },
      { name: 'strawberries', category: 'fruit', amount: '80', unit: 'g' },
      { name: 'honey', category: 'sweetener', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Beef Tacos',
    cookingTimeMin: 25,
    difficulty: 'easy',
    estimatedCost: 7.0,
    calories: 580,
    proteinG: 35,
    fatG: 28,
    carbsG: 40,
    steps: 'Brown ground beef with taco seasoning. Serve in tortillas with salsa, cheese and sour cream.',
    moodTags: ['happy', 'cozy'],
    ingredients: [
      { name: 'ground beef', category: 'meat', amount: '300', unit: 'g' },
      { name: 'corn tortillas', category: 'grain', amount: '4', unit: 'pcs' },
      { name: 'cheddar cheese', category: 'dairy', amount: '60', unit: 'g' },
      { name: 'sour cream', category: 'dairy', amount: '50', unit: 'g' },
      { name: 'salsa', category: 'condiment', amount: '80', unit: 'g' },
      { name: 'lettuce', category: 'vegetable', amount: '50', unit: 'g' },
    ],
  },
  {
    title: 'Mushroom Risotto',
    cookingTimeMin: 40,
    difficulty: 'hard',
    estimatedCost: 5.5,
    calories: 490,
    proteinG: 12,
    fatG: 18,
    carbsG: 72,
    steps: 'Sauté mushrooms, add arborio rice, ladle warm broth gradually, finish with parmesan.',
    moodTags: ['cozy', 'calm'],
    ingredients: [
      { name: 'arborio rice', category: 'grain', amount: '180', unit: 'g' },
      { name: 'mushrooms', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'parmesan', category: 'dairy', amount: '50', unit: 'g' },
      { name: 'butter', category: 'dairy', amount: '30', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'vegetable broth', category: 'liquid', amount: '600', unit: 'ml' },
      { name: 'white wine', category: 'alcohol', amount: '100', unit: 'ml' },
    ],
  },
  {
    title: 'Chickpea Buddha Bowl',
    cookingTimeMin: 30,
    difficulty: 'easy',
    estimatedCost: 4.0,
    calories: 430,
    proteinG: 20,
    fatG: 14,
    carbsG: 58,
    steps: 'Roast chickpeas with spices. Serve over rice with roasted sweet potato, spinach and tahini.',
    moodTags: ['calm', 'happy', 'energetic'],
    ingredients: [
      { name: 'chickpeas', category: 'legume', amount: '200', unit: 'g' },
      { name: 'sweet potato', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'brown rice', category: 'grain', amount: '80', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'tahini', category: 'condiment', amount: '2', unit: 'tbsp' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
      { name: 'cumin', category: 'spice', amount: '1', unit: 'tsp' },
    ],
  },

  // ─── Added for Epic 4 testing — fast, cheap, varied state/diet coverage ──────
  {
    title: 'Tuna Rice Bowl',
    cookingTimeMin: 10,
    difficulty: 'easy',
    estimatedCost: 3.5,
    calories: 480,
    proteinG: 38,
    fatG: 8,
    carbsG: 58,
    steps: 'Warm cooked rice, flake canned tuna on top, add corn and a drizzle of olive oil.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'canned tuna', category: 'fish', amount: '1', unit: 'can' },
      { name: 'white rice', category: 'grain', amount: '120', unit: 'g' },
      { name: 'sweet corn', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Egg Fried Rice',
    cookingTimeMin: 15,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 420,
    proteinG: 16,
    fatG: 12,
    carbsG: 62,
    steps: 'Fry day-old rice with beaten eggs, peas, carrot and a splash of soy sauce.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'white rice', category: 'grain', amount: '150', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'green peas', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'soy sauce', category: 'condiment', amount: '2', unit: 'tbsp' },
    ],
  },
  {
    title: 'Black Bean Burrito',
    cookingTimeMin: 15,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 450,
    proteinG: 18,
    fatG: 10,
    carbsG: 72,
    steps: 'Warm a tortilla, fill with spiced black beans, rice, corn and salsa, then roll.',
    moodTags: ['happy', 'energetic', 'cozy'],
    ingredients: [
      { name: 'black beans', category: 'legume', amount: '200', unit: 'g' },
      { name: 'flour tortilla', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'white rice', category: 'grain', amount: '80', unit: 'g' },
      { name: 'sweet corn', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'salsa', category: 'condiment', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Peanut Butter Oatmeal',
    cookingTimeMin: 7,
    difficulty: 'easy',
    estimatedCost: 2.0,
    calories: 380,
    proteinG: 14,
    fatG: 12,
    carbsG: 58,
    steps: 'Cook oats with milk, stir in peanut butter and top with banana slices.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'rolled oats', category: 'grain', amount: '60', unit: 'g' },
      { name: 'milk', category: 'dairy', amount: '200', unit: 'ml' },
      { name: 'peanut butter', category: 'nuts', amount: '1', unit: 'tbsp' },
      { name: 'banana', category: 'fruit', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Turkey Sweet Potato Bowl',
    cookingTimeMin: 25,
    difficulty: 'medium',
    estimatedCost: 6.5,
    calories: 500,
    proteinG: 40,
    fatG: 14,
    carbsG: 38,
    steps: 'Brown ground turkey, roast sweet potato cubes, combine with spinach and olive oil.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'ground turkey', category: 'meat', amount: '200', unit: 'g' },
      { name: 'sweet potato', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'spinach', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Miso Vegetable Soup',
    cookingTimeMin: 15,
    difficulty: 'easy',
    estimatedCost: 3.5,
    calories: 180,
    proteinG: 10,
    fatG: 6,
    carbsG: 18,
    steps: 'Simmer vegetable broth, whisk in miso paste, add tofu cubes, spring onion and seaweed.',
    moodTags: ['calm', 'cozy'],
    ingredients: [
      { name: 'miso paste', category: 'soy', amount: '2', unit: 'tbsp' },
      { name: 'tofu', category: 'soy', amount: '100', unit: 'g' },
      { name: 'vegetable broth', category: 'liquid', amount: '500', unit: 'ml' },
      { name: 'spring onion', category: 'vegetable', amount: '2', unit: 'pcs' },
    ],
  },
  {
    title: 'Cottage Cheese & Berry Bowl',
    cookingTimeMin: 5,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 240,
    proteinG: 24,
    fatG: 4,
    carbsG: 28,
    steps: 'Spoon cottage cheese into a bowl, top with mixed berries and a few seeds.',
    moodTags: ['calm', 'happy'],
    ingredients: [
      { name: 'cottage cheese', category: 'dairy', amount: '200', unit: 'g' },
      { name: 'blueberries', category: 'fruit', amount: '60', unit: 'g' },
      { name: 'strawberries', category: 'fruit', amount: '60', unit: 'g' },
      { name: 'pumpkin seeds', category: 'seeds', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Pork Ramen',
    cookingTimeMin: 35,
    difficulty: 'medium',
    estimatedCost: 7.0,
    calories: 600,
    proteinG: 32,
    fatG: 22,
    carbsG: 60,
    steps: 'Simmer pork belly in broth, cook ramen noodles, top with a soft-boiled egg and scallions.',
    moodTags: ['cozy', 'happy'],
    ingredients: [
      { name: 'pork belly', category: 'meat', amount: '150', unit: 'g' },
      { name: 'ramen noodles', category: 'grain', amount: '100', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '1', unit: 'pc' },
      { name: 'spring onion', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'soy sauce', category: 'condiment', amount: '2', unit: 'tbsp' },
    ],
  },
  {
    title: 'Spinach Mushroom Omelette',
    cookingTimeMin: 10,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 300,
    proteinG: 20,
    fatG: 18,
    carbsG: 8,
    steps: 'Sauté mushrooms and spinach, pour over beaten eggs and fold the omelette.',
    moodTags: ['energetic', 'focused', 'calm'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '3', unit: 'pcs' },
      { name: 'mushrooms', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '50', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Hummus Veggie Wrap',
    cookingTimeMin: 10,
    difficulty: 'easy',
    estimatedCost: 3.5,
    calories: 360,
    proteinG: 12,
    fatG: 12,
    carbsG: 50,
    steps: 'Spread hummus on a tortilla, add cucumber, bell pepper and greens, then roll.',
    moodTags: ['calm', 'happy', 'energetic'],
    ingredients: [
      { name: 'hummus', category: 'legume', amount: '4', unit: 'tbsp' },
      { name: 'flour tortilla', category: 'grain', amount: '1', unit: 'pc' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'mixed greens', category: 'vegetable', amount: '40', unit: 'g' },
    ],
  },

  // ─── Healthy expansion (Session 18) — balanced, student-friendly, quick ──────
  // Built around common fridge staples (eggs, cheese, yogurt, milk, bread,
  // bell pepper, sausage, oats, chicken, tuna, beans, rice, vegetables) so the
  // photo / pantry flows return meals people can actually cook.
  {
    title: 'Veggie Cheese Omelette',
    cookingTimeMin: 10,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 330,
    proteinG: 24,
    fatG: 22,
    carbsG: 6,
    steps: 'Beat eggs, pour into a hot non-stick pan, scatter diced bell pepper and grated cheese, fold once set.',
    moodTags: ['energetic', 'focused', 'happy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '3', unit: 'pcs' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tsp' },
    ],
  },
  {
    title: 'Cheese & Egg Toast',
    cookingTimeMin: 8,
    difficulty: 'easy',
    estimatedCost: 2.5,
    calories: 350,
    proteinG: 20,
    fatG: 16,
    carbsG: 30,
    steps: 'Toast bread, top with sliced cheese, melt under the grill, add a fried or poached egg.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'whole wheat bread', category: 'grain', amount: '2', unit: 'slices' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Scrambled Eggs with Sausage',
    cookingTimeMin: 12,
    difficulty: 'easy',
    estimatedCost: 4.0,
    calories: 420,
    proteinG: 28,
    fatG: 30,
    carbsG: 4,
    steps: 'Slice and brown the sausage, pour over beaten eggs and scramble gently until just set.',
    moodTags: ['cozy', 'energetic'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '3', unit: 'pcs' },
      { name: 'sausage', category: 'meat', amount: '1', unit: 'pc' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Greek Yogurt Bowl with Oats',
    cookingTimeMin: 5,
    difficulty: 'easy',
    estimatedCost: 2.5,
    calories: 300,
    proteinG: 22,
    fatG: 7,
    carbsG: 38,
    steps: 'Spoon Greek yogurt over rolled oats, let sit 2 minutes, top with fruit and a drizzle of honey.',
    moodTags: ['calm', 'happy', 'focused'],
    ingredients: [
      { name: 'greek yogurt', category: 'dairy', amount: '200', unit: 'g' },
      { name: 'rolled oats', category: 'grain', amount: '40', unit: 'g' },
      { name: 'banana', category: 'fruit', amount: '1', unit: 'pc' },
    ],
  },
  {
    title: 'Overnight Oats',
    cookingTimeMin: 5,
    difficulty: 'easy',
    estimatedCost: 2.0,
    calories: 340,
    proteinG: 14,
    fatG: 8,
    carbsG: 56,
    steps: 'Combine oats and milk in a jar, refrigerate overnight, top with berries before eating.',
    moodTags: ['calm', 'cozy'],
    ingredients: [
      { name: 'rolled oats', category: 'grain', amount: '60', unit: 'g' },
      { name: 'milk', category: 'dairy', amount: '180', unit: 'ml' },
      { name: 'blueberries', category: 'fruit', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Bell Pepper Egg Cups',
    cookingTimeMin: 18,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 220,
    proteinG: 18,
    fatG: 14,
    carbsG: 6,
    steps: 'Halve and deseed bell peppers, crack an egg into each, bake at 190°C until the white sets.',
    moodTags: ['focused', 'energetic', 'calm'],
    ingredients: [
      { name: 'bell pepper', category: 'vegetable', amount: '2', unit: 'pcs' },
      { name: 'eggs', category: 'dairy', amount: '4', unit: 'pcs' },
      { name: 'cheese', category: 'dairy', amount: '30', unit: 'g' },
    ],
  },
  {
    title: 'Tuna White Bean Salad',
    cookingTimeMin: 10,
    difficulty: 'easy',
    estimatedCost: 4.0,
    calories: 360,
    proteinG: 34,
    fatG: 10,
    carbsG: 30,
    steps: 'Drain tuna and beans, toss with chopped bell pepper, lemon juice and olive oil.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'canned tuna', category: 'fish', amount: '1', unit: 'can' },
      { name: 'beans', category: 'legume', amount: '150', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Chicken Veggie Rice Bowl',
    cookingTimeMin: 20,
    difficulty: 'easy',
    estimatedCost: 5.0,
    calories: 470,
    proteinG: 40,
    fatG: 12,
    carbsG: 48,
    steps: 'Pan-cook diced chicken, add bell pepper and spinach, serve over brown rice.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '180', unit: 'g' },
      { name: 'brown rice', category: 'grain', amount: '80', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'spinach', category: 'vegetable', amount: '50', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Lentil Vegetable Soup',
    cookingTimeMin: 30,
    difficulty: 'easy',
    estimatedCost: 2.5,
    calories: 320,
    proteinG: 18,
    fatG: 6,
    carbsG: 48,
    steps: 'Simmer red lentils with carrot, onion, tomato and cumin until soft and thick.',
    moodTags: ['calm', 'cozy', 'happy'],
    ingredients: [
      { name: 'red lentils', category: 'legume', amount: '150', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'cumin', category: 'spice', amount: '1', unit: 'tsp' },
    ],
  },
  {
    title: 'Chickpea Spinach Curry',
    cookingTimeMin: 25,
    difficulty: 'medium',
    estimatedCost: 3.5,
    calories: 410,
    proteinG: 18,
    fatG: 12,
    carbsG: 58,
    steps: 'Sauté onion and garlic, add chickpeas, tomato and spinach, simmer with curry spices.',
    moodTags: ['calm', 'cozy', 'energetic'],
    ingredients: [
      { name: 'chickpeas', category: 'legume', amount: '200', unit: 'g' },
      { name: 'spinach', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'canned tomatoes', category: 'vegetable', amount: '200', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
    ],
  },
  {
    title: 'Baked Salmon with Vegetables',
    cookingTimeMin: 25,
    difficulty: 'easy',
    estimatedCost: 8.0,
    calories: 440,
    proteinG: 40,
    fatG: 24,
    carbsG: 16,
    steps: 'Place salmon and chopped vegetables on a tray, drizzle olive oil and lemon, bake at 200°C.',
    moodTags: ['focused', 'energetic', 'calm'],
    ingredients: [
      { name: 'salmon', category: 'fish', amount: '180', unit: 'g' },
      { name: 'broccoli', category: 'vegetable', amount: '120', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
      { name: 'lemon', category: 'fruit', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Turkey Lettuce Wraps',
    cookingTimeMin: 15,
    difficulty: 'easy',
    estimatedCost: 5.0,
    calories: 300,
    proteinG: 32,
    fatG: 14,
    carbsG: 10,
    steps: 'Brown ground turkey with garlic and soy sauce, spoon into crisp lettuce leaves.',
    moodTags: ['energetic', 'focused'],
    ingredients: [
      { name: 'ground turkey', category: 'meat', amount: '200', unit: 'g' },
      { name: 'lettuce', category: 'vegetable', amount: '6', unit: 'leaves' },
      { name: 'garlic', category: 'vegetable', amount: '2', unit: 'cloves' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Quinoa Veggie Salad',
    cookingTimeMin: 20,
    difficulty: 'easy',
    estimatedCost: 4.0,
    calories: 380,
    proteinG: 14,
    fatG: 14,
    carbsG: 52,
    steps: 'Cook quinoa, cool, toss with cucumber, tomato, bell pepper, lemon and olive oil.',
    moodTags: ['calm', 'happy', 'energetic'],
    ingredients: [
      { name: 'quinoa', category: 'grain', amount: '80', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Cottage Cheese Veggie Bowl',
    cookingTimeMin: 5,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 250,
    proteinG: 26,
    fatG: 8,
    carbsG: 14,
    steps: 'Spoon cottage cheese into a bowl, add sliced cucumber, cherry tomatoes and a little olive oil.',
    moodTags: ['calm', 'focused', 'happy'],
    ingredients: [
      { name: 'cottage cheese', category: 'dairy', amount: '200', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tsp' },
    ],
  },
  {
    title: 'Veggie Fried Rice with Egg',
    cookingTimeMin: 15,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 400,
    proteinG: 16,
    fatG: 12,
    carbsG: 58,
    steps: 'Stir-fry cooked rice with mixed vegetables, push aside and scramble an egg, combine with soy sauce.',
    moodTags: ['cozy', 'happy', 'energetic'],
    ingredients: [
      { name: 'brown rice', category: 'grain', amount: '150', unit: 'g' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'green peas', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Mediterranean Chickpea Bowl',
    cookingTimeMin: 12,
    difficulty: 'easy',
    estimatedCost: 3.5,
    calories: 390,
    proteinG: 16,
    fatG: 14,
    carbsG: 52,
    steps: 'Toss chickpeas with cucumber, tomato, feta and olive oil, season with lemon and herbs.',
    moodTags: ['calm', 'happy', 'focused'],
    ingredients: [
      { name: 'chickpeas', category: 'legume', amount: '200', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'cherry tomatoes', category: 'vegetable', amount: '80', unit: 'g' },
      { name: 'feta', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Banana Peanut Yogurt Bowl',
    cookingTimeMin: 5,
    difficulty: 'easy',
    estimatedCost: 2.5,
    calories: 330,
    proteinG: 20,
    fatG: 12,
    carbsG: 36,
    steps: 'Top Greek yogurt with sliced banana and a spoon of peanut butter.',
    moodTags: ['cozy', 'calm', 'happy'],
    ingredients: [
      { name: 'greek yogurt', category: 'dairy', amount: '200', unit: 'g' },
      { name: 'banana', category: 'fruit', amount: '1', unit: 'pc' },
      { name: 'peanut butter', category: 'nuts', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Vegetable Frittata',
    cookingTimeMin: 22,
    difficulty: 'medium',
    estimatedCost: 4.0,
    calories: 360,
    proteinG: 24,
    fatG: 24,
    carbsG: 10,
    steps: 'Sauté mixed vegetables, pour over beaten eggs with cheese, finish in the oven until set.',
    moodTags: ['energetic', 'focused', 'cozy'],
    ingredients: [
      { name: 'eggs', category: 'dairy', amount: '4', unit: 'pcs' },
      { name: 'bell pepper', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'spinach', category: 'vegetable', amount: '50', unit: 'g' },
      { name: 'cheese', category: 'dairy', amount: '40', unit: 'g' },
      { name: 'onion', category: 'vegetable', amount: '0.5', unit: 'pc' },
    ],
  },
  {
    title: 'Black Bean Veggie Bowl',
    cookingTimeMin: 15,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 420,
    proteinG: 18,
    fatG: 10,
    carbsG: 66,
    steps: 'Warm black beans with cumin, serve over rice with corn, bell pepper and salsa.',
    moodTags: ['happy', 'energetic', 'cozy'],
    ingredients: [
      { name: 'black beans', category: 'legume', amount: '200', unit: 'g' },
      { name: 'brown rice', category: 'grain', amount: '80', unit: 'g' },
      { name: 'sweet corn', category: 'vegetable', amount: '60', unit: 'g' },
      { name: 'bell pepper', category: 'vegetable', amount: '0.5', unit: 'pc' },
      { name: 'salsa', category: 'condiment', amount: '60', unit: 'g' },
    ],
  },
  {
    title: 'Oat Banana Pancakes',
    cookingTimeMin: 15,
    difficulty: 'easy',
    estimatedCost: 2.5,
    calories: 340,
    proteinG: 16,
    fatG: 10,
    carbsG: 48,
    steps: 'Blend oats, banana and eggs into a batter, cook small pancakes in a non-stick pan.',
    moodTags: ['happy', 'cozy', 'energetic'],
    ingredients: [
      { name: 'rolled oats', category: 'grain', amount: '60', unit: 'g' },
      { name: 'banana', category: 'fruit', amount: '1', unit: 'pc' },
      { name: 'eggs', category: 'dairy', amount: '2', unit: 'pcs' },
    ],
  },
  {
    title: 'Tomato Cucumber Cheese Salad',
    cookingTimeMin: 8,
    difficulty: 'easy',
    estimatedCost: 3.0,
    calories: 260,
    proteinG: 12,
    fatG: 18,
    carbsG: 12,
    steps: 'Chop tomato and cucumber, add cubed cheese, dress with olive oil and a pinch of salt.',
    moodTags: ['calm', 'happy'],
    ingredients: [
      { name: 'cherry tomatoes', category: 'vegetable', amount: '120', unit: 'g' },
      { name: 'cucumber', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'cheese', category: 'dairy', amount: '60', unit: 'g' },
      { name: 'olive oil', category: 'oil', amount: '1', unit: 'tbsp' },
    ],
  },
  {
    title: 'Chicken Vegetable Soup',
    cookingTimeMin: 30,
    difficulty: 'easy',
    estimatedCost: 4.5,
    calories: 280,
    proteinG: 30,
    fatG: 8,
    carbsG: 22,
    steps: 'Simmer diced chicken with carrot, celery, onion and herbs until tender.',
    moodTags: ['cozy', 'calm', 'focused'],
    ingredients: [
      { name: 'chicken breast', category: 'meat', amount: '150', unit: 'g' },
      { name: 'carrot', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'onion', category: 'vegetable', amount: '1', unit: 'pc' },
      { name: 'spinach', category: 'vegetable', amount: '40', unit: 'g' },
    ],
  },
  {
    title: 'Tofu Veggie Bowl',
    cookingTimeMin: 18,
    difficulty: 'easy',
    estimatedCost: 4.0,
    calories: 350,
    proteinG: 22,
    fatG: 16,
    carbsG: 30,
    steps: 'Pan-fry tofu cubes until golden, toss with steamed broccoli and brown rice, drizzle soy sauce.',
    moodTags: ['calm', 'energetic', 'focused'],
    ingredients: [
      { name: 'tofu', category: 'soy', amount: '200', unit: 'g' },
      { name: 'broccoli', category: 'vegetable', amount: '120', unit: 'g' },
      { name: 'brown rice', category: 'grain', amount: '80', unit: 'g' },
      { name: 'soy sauce', category: 'condiment', amount: '1', unit: 'tbsp' },
    ],
  },
]

// Full catalogue = original curated recipes + the Session 20 healthy expansion.
const recipes = [...baseRecipes, ...extraRecipes]

async function main() {
  // ─── Subscription plans ──────────────────────────────────────────────────
  console.log('Seeding subscription plans...')

  await prisma.subscriptionPlan.upsert({
    where:  { type: 'monthly' },
    create: { type: 'monthly', name: 'Monthly', priceKzt: 2990, priceUsd: 9.99, durationDays: 30,  description: 'Full access for 1 month' },
    update: { name: 'Monthly', priceKzt: 2990, priceUsd: 9.99, durationDays: 30,  description: 'Full access for 1 month', isActive: true },
  })

  await prisma.subscriptionPlan.upsert({
    where:  { type: 'annual' },
    create: { type: 'annual', name: 'Annual', priceKzt: 24990, priceUsd: 79.99, durationDays: 365, description: 'Full access for 1 year — save 30%' },
    update: { name: 'Annual', priceKzt: 24990, priceUsd: 79.99, durationDays: 365, description: 'Full access for 1 year — save 30%', isActive: true },
  })

  console.log('  ✓ Monthly (2,990 KZT / $9.99 / 30 days)')
  console.log('  ✓ Annual  (24,990 KZT / $79.99 / 365 days)')

  // ─── Recipes ─────────────────────────────────────────────────────────────
  // Idempotent: recipes are matched by title, so re-running the seed (incl. on
  // the production DB) does not create duplicates. Recipe.title has no unique
  // constraint, so we guard with findFirst rather than upsert.
  console.log('\nSeeding recipes...')

  let created = 0
  let skipped = 0

  for (const r of recipes) {
    const existing = await prisma.recipe.findFirst({
      where: { title: r.title },
      select: { id: true },
    })
    if (existing) {
      skipped++
      console.log(`  • ${r.title} (already exists, skipped)`)
      continue
    }

    const recipe = await prisma.recipe.create({
      data: {
        title: r.title,
        cookingTimeMin: r.cookingTimeMin,
        difficulty: r.difficulty,
        estimatedCost: r.estimatedCost,
        calories: r.calories,
        proteinG: r.proteinG,
        fatG: (r as any).fatG ?? null,
        carbsG: (r as any).carbsG ?? null,
        steps: r.steps,
        moodTags: r.moodTags,
      },
    })

    for (const ing of r.ingredients) {
      const ingredient = await prisma.ingredient.upsert({
        where: { name: ing.name },
        create: { name: ing.name, category: ing.category },
        update: {},
      })

      await prisma.recipeIngredient.create({
        data: {
          recipeId: recipe.id,
          ingredientId: ingredient.id,
          amount: ing.amount,
          unit: ing.unit,
        },
      })
    }

    created++
    console.log(`  ✓ ${recipe.title}`)
  }

  console.log(`\nDone — 2 plans + ${created} new recipes (${skipped} skipped, ${recipes.length} total).`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
